from building import *
Import('RTT_ROOT')

cwd = GetCurrentDir()
src = Split("""
block_dev.c
mmcsd_core.c
sd.c
sdio.c
gpt.c
mmc.c
""")

# The set of source files associated with this SConscript file.
path = [cwd + '/../include']

group = DefineGroup('DeviceDrivers', src, depend=[
                    'RT_USING_SDIO'], CPPPATH=path)

Return('group')
