# for module compiling
from building import *
import os
Import('remove_components')

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if item in remove_components:
        continue

    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
